"""
OAuth Consent Flow Helpers

Utilities for managing customer consent for multi-tenant app access.
"""
import os
from urllib.parse import urlencode
from typing import Optional
import structlog

logger = structlog.get_logger(__name__)


# Default permissions required for security assessment
DEFAULT_GRAPH_SCOPES = [
    "https://graph.microsoft.com/.default",
]


def generate_consent_url(
    client_id: str,
    redirect_uri: str,
    tenant_id: Optional[str] = None,
    state: Optional[str] = None,
) -> str:
    """
    Generate admin consent URL for a customer to authorize your app.
    
    This creates a URL that the customer's Global Admin can click to
    grant your app access to their tenant.
    
    Args:
        client_id: Your multi-tenant app's client ID
        redirect_uri: Where to redirect after consent (your callback URL)
        tenant_id: Customer's tenant ID (optional, use 'common' for any tenant)
        state: Optional state parameter for CSRF protection
        
    Returns:
        Admin consent URL
        
    Example:
        >>> url = generate_consent_url(
        ...     client_id="your-app-id",
        ...     redirect_uri="https://yourapp.com/auth/callback",
        ... )
        >>> print(f"Send this to customer: {url}")
    """
    tenant = tenant_id or "common"
    
    params = {
        "client_id": client_id,
        "redirect_uri": redirect_uri,
        "scope": " ".join(DEFAULT_GRAPH_SCOPES),
    }
    
    if state:
        params["state"] = state
    
    base_url = f"https://login.microsoftonline.com/{tenant}/adminconsent"
    
    return f"{base_url}?{urlencode(params)}"


def generate_consent_email(
    customer_name: str,
    customer_admin_email: str,
    consent_url: str,
    your_company: str = "OperationMOS",
) -> dict:
    """
    Generate email content to send to customer requesting consent.
    
    Args:
        customer_name: Customer's organization name
        customer_admin_email: Email of customer's Global Admin
        consent_url: The consent URL generated by generate_consent_url()
        your_company: Your company name
        
    Returns:
        Dictionary with 'subject' and 'body' for the email
    """
    subject = f"Security Assessment Authorization Request - {your_company}"
    
    body = f"""
Dear {customer_name} Administrator,

Thank you for choosing {your_company} for your security assessment.

To proceed with the assessment, we need your authorization to read security 
configuration data from your Microsoft 365 and Azure environment. This is a 
one-time authorization that grants us read-only access.

**What We Access:**
• Microsoft Secure Score
• Identity Protection data (MFA status, risky users)
• Conditional Access policies
• Role assignments
• Device compliance status
• Security alerts
• Audit logs

**What We DON'T Access:**
• Email content
• Files or documents
• User passwords
• Write/modify permissions

**Authorization Steps:**
1. Click the link below (requires Global Administrator role)
2. Review the permissions listed
3. Click "Accept" to authorize

Authorization Link:
{consent_url}

After authorization, we will begin the assessment and provide you with a 
comprehensive security report within 2-3 business days.

If you have any questions, please don't hesitate to reach out.

Best regards,
{your_company} Security Team

---
This authorization can be revoked at any time from:
Azure Portal > Enterprise Applications > {your_company} Security Assessment > Permissions
"""
    
    return {
        "to": customer_admin_email,
        "subject": subject,
        "body": body.strip(),
    }


def validate_consent(tenant_id: str, client_id: str, client_secret: str) -> dict:
    """
    Validate that consent has been granted for a tenant.
    
    Attempts to acquire a token for the tenant. If successful,
    consent is valid.
    
    Args:
        tenant_id: Customer's tenant ID
        client_id: Your app's client ID
        client_secret: Your app's client secret
        
    Returns:
        Dictionary with validation result
    """
    from azure.identity import ClientSecretCredential
    from azure.core.exceptions import ClientAuthenticationError
    
    try:
        credential = ClientSecretCredential(
            tenant_id=tenant_id,
            client_id=client_id,
            client_secret=client_secret,
        )
        
        # Attempt to get a token
        token = credential.get_token("https://graph.microsoft.com/.default")
        
        if token:
            logger.info("consent_validated", tenant_id=tenant_id)
            return {
                "valid": True,
                "tenant_id": tenant_id,
                "message": "Consent is valid",
            }
        else:
            return {
                "valid": False,
                "tenant_id": tenant_id,
                "message": "Could not acquire token",
            }
            
    except ClientAuthenticationError as e:
        error_message = str(e)
        
        if "AADSTS65001" in error_message:
            # Admin consent required
            return {
                "valid": False,
                "tenant_id": tenant_id,
                "message": "Admin consent required - customer has not authorized the app",
                "consent_required": True,
            }
        elif "AADSTS700016" in error_message:
            # App not found in tenant
            return {
                "valid": False,
                "tenant_id": tenant_id,
                "message": "App not found in tenant - consent has not been granted",
                "consent_required": True,
            }
        else:
            return {
                "valid": False,
                "tenant_id": tenant_id,
                "message": f"Authentication error: {error_message}",
            }
    except Exception as e:
        logger.error("consent_validation_error", error=str(e))
        return {
            "valid": False,
            "tenant_id": tenant_id,
            "message": f"Unexpected error: {str(e)}",
        }


def list_consented_tenants(client_id: str) -> list[dict]:
    """
    List all tenants that have consented to your app.
    
    Note: This requires Azure AD Premium or Microsoft Graph API access
    to query service principals across tenants.
    
    Args:
        client_id: Your app's client ID
        
    Returns:
        List of tenant information dictionaries
    """
    # In a production implementation, this would query your database
    # of consented tenants, or use the Microsoft Graph API to enumerate
    # service principals created by consent.
    #
    # For now, return empty list - tenants should be tracked in your
    # own database when consent callbacks are received.
    
    logger.warning("list_consented_tenants not fully implemented")
    return []


def revoke_consent_instructions(tenant_id: str, app_name: str) -> str:
    """
    Generate instructions for customer to revoke consent.
    
    Args:
        tenant_id: Customer's tenant ID
        app_name: Your app's display name
        
    Returns:
        Instructions text
    """
    return f"""
To revoke access for {app_name}:

1. Sign in to Azure Portal (https://portal.azure.com)
2. Navigate to: Azure Active Directory > Enterprise Applications
3. Search for: {app_name}
4. Click on the application
5. Go to: Permissions
6. Click: "Revoke admin consent"

Alternatively, a Global Administrator can remove the service principal:
1. Navigate to: Enterprise Applications > {app_name}
2. Click: Properties
3. Click: Delete

After revocation, {app_name} will no longer have access to your tenant.
"""
